name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.16.3

    - name: Install dependencies
      run: yarn install

    - name: Skip tests
      run: echo "skipping tests"

    - name: Build project
      run: yarn build

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      run: |
        aws s3 sync build/ s3://$S3_BUCKET --delete
